//
//  Copyright © 2026 Apparata AB. All rights reserved.
//

import Foundation

/// Emits `swift-token-mapping.swift` — an `import SwiftUI` file containing
/// an `extension Color` referencing every semantic color by camelCase name,
/// plus companion enums for spacing and radius numeric constants.
///
/// Colors are looked up by asset-catalog name (the camelCased semantic name)
/// in the sibling `DesignTokens.xcassets/`, which the `AssetCatalogExporter`
/// produces in the same pass. Consumers drop both artifacts into their
/// Xcode project or Swift package and get light/dark behavior for free.
///
/// Errors:
/// - Two or more semantic names that collapse to the same camelCase
///   identifier are returned as a `SwiftExportError.identifierCollisions`
///   so the export command can block before writing anything.
///
nonisolated enum SwiftExporter {

    static func export(_ spec: TokenforgeSpec, resolver: TokenResolver) throws -> Data {
        let colorNames = spec.semantic.color.map(\.name)
        let colorCollisions = IdentifierCase.collisions(in: colorNames)
        if !colorCollisions.isEmpty {
            throw SwiftExportError.identifierCollisions(category: "color", colliding: colorCollisions)
        }

        let spacingNames = spec.semantic.spacing.map(\.name)
        let spacingCollisions = IdentifierCase.collisions(in: spacingNames)
        if !spacingCollisions.isEmpty {
            throw SwiftExportError.identifierCollisions(category: "spacing", colliding: spacingCollisions)
        }

        let radiusNames = spec.semantic.radius.map(\.name)
        let radiusCollisions = IdentifierCase.collisions(in: radiusNames)
        if !radiusCollisions.isEmpty {
            throw SwiftExportError.identifierCollisions(category: "radius", colliding: radiusCollisions)
        }

        var source = ""
        source.append(fileHeader(spec: spec))
        source.append("\n")
        source.append(colorExtension(spec: spec))
        source.append("\n")
        source.append(spacingExtension(spec: spec, resolver: resolver))
        source.append("\n")
        source.append(radiusExtension(spec: spec, resolver: resolver))
        source.append("\n")
        return Data(source.utf8)
    }

    // MARK: - File header

    private static func fileHeader(spec: TokenforgeSpec) -> String {
        """
        // Generated by Tokenforge. Do not edit by hand.
        // Source: \(spec.meta.name) (schemaVersion \(spec.schemaVersion))
        //
        // This file is regenerated on every Export All run; hand edits will
        // be overwritten.

        import SwiftUI

        """
    }

    // MARK: - Color

    private static func colorExtension(spec: TokenforgeSpec) -> String {
        var lines: [String] = []
        lines.append("public extension Color {")
        lines.append("")
        for entry in spec.semantic.color {
            let identifier = IdentifierCase.camelCase(from: entry.name)
            let assetName = identifier
            lines.append("    /// Semantic color `\(entry.name)`.")
            lines.append("    static let \(identifier) = Color(\"\(assetName)\", bundle: .main)")
        }
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    // MARK: - Spacing

    private static func spacingExtension(spec: TokenforgeSpec, resolver: TokenResolver) -> String {
        var lines: [String] = []
        lines.append("public enum AppSpacing {")
        lines.append("")
        for alias in spec.semantic.spacing {
            let identifier = IdentifierCase.camelCase(from: alias.name)
            let value = Self.pointValue(for: alias.reference, resolver: resolver) ?? 0
            lines.append("    /// Semantic spacing `\(alias.name)`.")
            lines.append("    public static let \(identifier): CGFloat = \(Self.formatCGFloat(value))")
        }
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    // MARK: - Radius

    private static func radiusExtension(spec: TokenforgeSpec, resolver: TokenResolver) -> String {
        var lines: [String] = []
        lines.append("public enum AppRadius {")
        lines.append("")
        for alias in spec.semantic.radius {
            let identifier = IdentifierCase.camelCase(from: alias.name)
            let value = Self.pointValue(for: alias.reference, resolver: resolver) ?? 0
            lines.append("    /// Semantic radius `\(alias.name)`.")
            lines.append("    public static let \(identifier): CGFloat = \(Self.formatCGFloat(value))")
        }
        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    private static func pointValue(for ref: TokenRef, resolver: TokenResolver) -> Double? {
        if case .points(let value) = resolver.resolve(ref) {
            return value
        }
        return nil
    }

    private static func formatCGFloat(_ value: Double) -> String {
        if value.rounded() == value {
            return String(format: "%.0f", value)
        }
        return String(format: "%.4g", value)
    }
}

// MARK: - Errors

nonisolated enum SwiftExportError: Error, CustomStringConvertible {
    case identifierCollisions(category: String, colliding: [(identifier: String, sources: [String])])

    var description: String {
        switch self {
        case .identifierCollisions(let category, let colliding):
            let lines = colliding.map { entry in
                "\(entry.identifier) ← \(entry.sources.joined(separator: ", "))"
            }
            return "Swift identifier collision(s) in semantic.\(category):\n" + lines.joined(separator: "\n")
        }
    }
}
