//
//  Copyright © 2026 Apparata AB. All rights reserved.
//

import SwiftUI
// Font package generated by https://github.com/apparata/mkfont
//import WhateverFont

// MARK: - App Text Styles

extension Font {

    public struct Theme {

        /// Whatever, Bold, 24
        //public static let heading1 = Font.Somefont.fixed(.bold, size: 24)

        /// Whatever, Medium, 16
        //public static let bodyRegular = Font.Somefont.fixed(.medium, size: 16)

        // ...
    }
}
